name: Bug Report
description: Report a bug
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: environment
    attributes:
      label: Environment (browser, OS)
