name: Feature Request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
  - type: textarea
    id: rationale
    attributes:
      label: Rationale / Use Case
